EQUIPMENT_LIST = "/equipments"
EQUIPMENT_CREATE = "/equipments"
EQUIPMENT_DETAIL = "/equipments/{equipment_it:str}"
EQUIPMENT_UPDATE = "/equipments/{equipment_it:str}"
EQUIPMENT_DELETE = "/equipments/{equipment_it:str}"
