EMPLOYEE_LIST = "/employees"
EMPLOYEE_LIST_WEB = "/employees/web"
EMPLOYEE_CREATE = "/employees"
EMPLOYEE_DETAIL = "/employees/{employee_slug:str}"
EMPLOYEE_UPDATE = "/employees/{employee_slug:str}"
EMPLOYEE_DELETE = "/employees/{employee_slug:str}"
