DEPARTMENT_LIST = "/departments"
DEPARTMENT_LIST_WEB = "/departments/web"
DEPARTMENT_CREATE = "/departments"
DEPARTMENT_DETAIL = "/departments/{department_slug:str}"
DEPARTMENT_UPDATE = "/departments/{department_slug:str}"
DEPARTMENT_DELETE = "/departments/{department_slug:str}"
