# type: ignore
"""First create tables

Revision ID: 7751a1c9e3fc
Revises:
Create Date: 2025-02-11 19:12:55.347634+00:00

"""

from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import (
    EncryptedString,
    EncryptedText,
    GUID,
    ORA_JSONB,
    DateTimeUTC,
)
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    pass

__all__ = [
    "downgrade",
    "upgrade",
    "schema_upgrades",
    "schema_downgrades",
    "data_upgrades",
    "data_downgrades",
]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText

# revision identifiers, used by Alembic.
revision = "7751a1c9e3fc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departments",
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "type",
            sa.Enum("UPOGG", "OPK", "POGZ", "STORAGE", name="departmenttype"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_departments")),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("name", name=op.f("uq_departments_name")),
        sa.UniqueConstraint("slug", name="uq_departments_slug"),
    )
    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.create_index("ix_departments_slug_unique", ["slug"], unique=True)

    op.create_table(
        "documents",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("doc_number", sa.String(length=10), nullable=False),
        sa.Column("doc_date", sa.Date(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
    )
    op.create_table(
        "employees",
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("fullname", sa.String(length=100), nullable=False),
        sa.Column("card_number", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("slug", name=op.f("pk_employees")),
        sa.UniqueConstraint("fullname"),
        sa.UniqueConstraint("fullname", name=op.f("uq_employees_fullname")),
        sa.UniqueConstraint("slug", name="uq_employees_slug"),
    )
    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.create_index("ix_employees_slug_unique", ["slug"], unique=True)

    op.create_table(
        "equipment_names",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("nomenclature_code", sa.String(length=15), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_equipment_names")),
        sa.UniqueConstraint("nomenclature_code"),
        sa.UniqueConstraint(
            "nomenclature_code", name=op.f("uq_equipment_names_nomenclature_code")
        ),
    )
    op.create_table(
        "equipment",
        sa.Column("it", sa.String(length=7), nullable=False),
        sa.Column(
            "name_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=False,
        ),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("serial_number", sa.String(length=50), nullable=False),
        sa.Column("manufacture_date", sa.String(length=7), nullable=True),
        sa.Column("arrival_date", sa.String(length=7), nullable=True),
        sa.Column(
            "document_in_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "document_out_id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "EXPLOITED",
                "INTERNET",
                "SVT",
                "FAULTY",
                "RESERVE",
                "WRITE_OFF",
                name="equipmentstatus",
            ),
            nullable=False,
        ),
        sa.Column("employee_id", sa.String(), nullable=True),
        sa.Column("department_id", sa.String(), nullable=True),
        sa.Column("form_number", sa.String(length=5), nullable=True),
        sa.Column("location", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.String(), nullable=True),
        sa.CheckConstraint(
            "(employee_id IS NULL) != (department_id IS NULL)",
            name=op.f("ck_equipment_check_employee_or_department"),
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.slug"],
            name=op.f("fk_equipment_department_id_departments"),
        ),
        sa.ForeignKeyConstraint(
            ["document_in_id"],
            ["documents.id"],
            name=op.f("fk_equipment_document_in_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["document_out_id"],
            ["documents.id"],
            name=op.f("fk_equipment_document_out_id_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.slug"],
            name=op.f("fk_equipment_employee_id_employees"),
        ),
        sa.ForeignKeyConstraint(
            ["name_id"],
            ["equipment_names.id"],
            name=op.f("fk_equipment_name_id_equipment_names"),
        ),
        sa.PrimaryKeyConstraint("it", name=op.f("pk_equipment")),
    )
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("equipment")
    op.drop_table("equipment_names")
    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.drop_index("ix_employees_slug_unique")

    op.drop_table("employees")
    op.drop_table("documents")
    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.drop_index("ix_departments_slug_unique")

    op.drop_table("departments")
    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
